version: "3.3"
services:
  matchagana-app:
    image: matchagana
    build:
      context: .
    container_name: matchagana-app
#    env_file:
#      - ./.env
#    environment:
#      - MONGO_USERNAME=$DATABASE_USERNAME
#      - MONGO_PASSWORD=$DATABASE_PASSWORD
#      - MONGO_HOST=matchagana-db
#      - MONGO_PORT=$DATABASE_PORT
#      - MONGO_DB=$DATABASE
#    ports:
#      - "5000:5000"

  matchagana-db:
    image: mongo:latest
    container_name: matchagana-db
#    env_file: .env
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=$DATABASE_ROOT_USERNAME
#      - MONGO_INITDB_ROOT_PASSWORD=$DATABASE_ROOT_PASSWORD
#      - MONGO_INITDB_DATABASE=$DATABASE
#      - DATABASE_USERNAME=$DATABASE_USERNAME
#      - DATABASE_PASSWORD=$DATABASE_PASSWORD
#      - MONGO_PORT=$DATABASE_PORT
#    ports:
#      - "27017:27017"
    volumes:
      - ./data/db/:/data/db/
